<?php
/**
 * @file ding_page.module
 * Provides the page node type for the Ding! project.
 */

/**
 * Implementation of hook_form_alter().
 */
function ding_page_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'page_node_form') {
    // Hide the comment settings form and disable comments.
    unset($form['comment_settings']);
    $form['comment'] = array(
      '#type' => 'value',
      '#value' => 0,
    );
  }
  if($form_id == 'ding_library_admin_settings_main_form'){
    // Since we're adding an option to the form, the placeholder is no
    // longer needed.
    unset($form['placeholder']);

    $form['ding_page_skip_first_menu_level'] = array(
      '#type' => 'checkbox',
      '#title' => t('Skips the first menu level if menu organisation is chosen for a page.'),
      '#description' => t('This gives you the opportunity to have diffrent left menus on your "organisation" pages'),
      '#default_value' => variable_get('ding_page_skip_first_menu_level', FALSE),
    );
  }
}

include_once('ding_page.features.inc');